package widget

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/page/add_spending/widget/input_spending.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:spending_management/constants/app_styles.dart';
import 'package:flutter/material.dart';

Widget inputSpending({
  required IconData icon,
  required Color color,
  required TextEditingController controller,
  required String hintText,
  Function(String value)? action,
  TextInputAction? textInputAction,
  TextInputType? keyboardType,
  TextCapitalization textCapitalization = TextCapitalization.none,
}) {
  return Row(
    children: [
      Icon(icon, color: color, size: 30),
      const SizedBox(width: 10),
      Expanded(
        child: TextFormField(
          controller: controller,
          style: AppStyles.p,
          keyboardType: keyboardType,
          textInputAction: textInputAction,
          textCapitalization: textCapitalization,
          onFieldSubmitted: (value) {
            if (action != null) action(value);
          },
          decoration: InputDecoration(
            border: InputBorder.none,
            hintText: hintText,
            hintStyle: AppStyles.p,
          ),
        ),
      ),
    ],
  );
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
// TODO: add functions / types translated from the Dart file above.
