package widget

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/page/add_spending/widget/more_button.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:spending_management/constants/app_styles.dart';
import 'package:spending_management/setting/localization/app_localizations.dart';
import 'package:flutter/material.dart';

class MoreButton extends StatelessWidget {
  const MoreButton({Key? key, required this.action, required this.more})
      : super(key: key);
  final Function action;
  final bool more;

  @override
  Widget build(BuildContext context) {
    return TextButton(
      onPressed: () {
        action();
      },
      style: ButtonStyle(
        overlayColor: MaterialStateProperty.all(Colors.transparent),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            more
                ? AppLocalizations.of(context).translate('hide_away')
                : AppLocalizations.of(context).translate('more_details'),
            style: AppStyles.p,
          ),
          Icon(more ? Icons.arrow_drop_up : Icons.arrow_drop_down)
        ],
      ),
    );
  }
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
type MoreButton struct {
	// TODO: add fields translated from Dart
}

