package widget

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/page/add_spending/widget/pick_image_widget.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:spending_management/constants/function/pick_function.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

Widget pickImageWidget({required Function(XFile? file) image}) {
  return IntrinsicHeight(
    child: Row(
      children: [
        Expanded(
          child: IconButton(
            splashColor: Colors.transparent,
            highlightColor: Colors.transparent,
            onPressed: () async {
              var file = await pickImage(true);
              image(file);
            },
            icon: const Icon(Icons.image, size: 30),
          ),
        ),
        const VerticalDivider(
          color: Colors.black54,
          thickness: 1,
          indent: 5,
          endIndent: 5,
        ),
        Expanded(
          child: IconButton(
            splashColor: Colors.transparent,
            highlightColor: Colors.transparent,
            onPressed: () async {
              var file = await pickImage(false);
              image(file);
            },
            icon: const Icon(Icons.camera_alt, size: 30),
          ),
        ),
      ],
    ),
  );
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
// TODO: add functions / types translated from the Dart file above.
