package bloc

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/page/login/bloc/login_state.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
enum Social { email, google, facebook, newUser }

abstract class LoginState {}

class InitState extends LoginState {}

class LoginSuccessState extends LoginState {
  final Social social;
  LoginSuccessState({required this.social});
}

class LoginErrorState extends LoginState {
  String status;
  LoginErrorState({required this.status});
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
type LoginState struct {
	// TODO: add fields translated from Dart
}

type InitState struct {
	// TODO: add fields translated from Dart
}

type LoginSuccessState struct {
	// TODO: add fields translated from Dart
}

type LoginErrorState struct {
	// TODO: add fields translated from Dart
}

