package bloc

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/page/login/bloc/login_event.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
abstract class LoginEvent {}

class LoginWithEmailPasswordEvent extends LoginEvent {
  final String email;
  final String password;

  LoginWithEmailPasswordEvent({required this.email, required this.password});
}

class LoginWithGoogleEvent extends LoginEvent {}

class LoginWithFacebookEvent extends LoginEvent {}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
type LoginEvent struct {
	// TODO: add fields translated from Dart
}

type LoginWithEmailPasswordEvent struct {
	// TODO: add fields translated from Dart
}

type LoginWithGoogleEvent struct {
	// TODO: add fields translated from Dart
}

type LoginWithFacebookEvent struct {
	// TODO: add fields translated from Dart
}

