package function

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/constants/function/find_index.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:spending_management/models/spending.dart';

int findIndex(List<Spending> spendingList, String id) {
  for (int i = 0; i < spendingList.length; i++) {
    if (spendingList[i].id!.compareTo(id) == 0) {
      return i;
    }
  }

  return -1;
}
----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
// TODO: add functions / types translated from the Dart file above.
