package function

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/constants/function/get_data_spending.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:intl/intl.dart';

bool isSameMonth(DateTime day1, DateTime day2) =>
    day1.year == day2.year && day1.month == day2.month;

List<String> getDataSpending(
    {required Map<String, dynamic> data,
    required int index,
    required DateTime date}) {
  List<String> list = [];
  if (index == 0) {
    int weekDay = date.weekday;
    DateTime firstDayOfWeek = date.subtract(Duration(days: weekDay - 1));
    DateTime lastDayOfWeek = firstDayOfWeek.add(const Duration(days: 6));
    if (data[DateFormat("MM_yyyy").format(firstDayOfWeek)] != null) {
      list =
          (data[DateFormat("MM_yyyy").format(firstDayOfWeek)] as List<dynamic>)
              .map((e) => e.toString())
              .toList();
    }
    if (!isSameMonth(firstDayOfWeek, lastDayOfWeek) &&
        data[DateFormat("MM_yyyy").format(lastDayOfWeek)] != null) {
      list.addAll(
          (data[DateFormat("MM_yyyy").format(lastDayOfWeek)] as List<dynamic>)
              .map((e) => e.toString())
              .toList());
    }
  } else if (index == 1 && data[DateFormat("MM_yyyy").format(date)] != null) {
    list = (data[DateFormat("MM_yyyy").format(date)] as List<dynamic>)
        .map((e) => e.toString())
        .toList();
  } else if (index == 2) {
    for (int i = 1; i < 13; i++) {
      String dateString = DateFormat("MM_yyyy").format(DateTime(date.year, i));
      if (data[dateString] != null) {
        list.addAll((data[dateString] as List<dynamic>)
            .map((e) => e.toString())
            .toList());
      }
    }
  }
  return list;
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
// TODO: add functions / types translated from the Dart file above.
