package function

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/constants/function/list_categories.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
List categories = [
  {"name": 'eating', "icon": "assets/category/eat.png"},
  {"name": "living", "icon": "assets/category/soap.png"},
  {"name": "clothes", "icon": "assets/category/clothes.png"},
  {"name": "cosmetics", "icon": "assets/category/make-up.png"},
  {"name": "exchange", "icon": "assets/category/champagne-glass.png"},
  {"name": "medical", "icon": "assets/category/medicine.png"},
  {"name": "education", "icon": "assets/category/education.png"},
  {"name": "electricity", "icon": "assets/category/payments.png"},
  {"name": "commuting", "icon": "assets/category/car.png"},
  {"name": "contact", "icon": "assets/category/smartphone-iphone.png"},
  {"name": "house", "icon": "assets/category/home.png"},
  {"name": "add_category", "icon": "assets/category/add.png"},
];

List income = [
  {"name": 'salary', "icon": "assets/category/salary.png"},
  {"name": 'charity', "icon": "assets/category/charity.png"},
  {"name": 'bonus', "icon": "assets/category/bonus.png"},
  {"name": 'invest', "icon": "assets/category/invest.png"},
  {"name": 'paycheck', "icon": "assets/category/paycheck.png"},
  {"name": "add_category", "icon": "assets/category/add.png"},
];

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
// TODO: add functions / types translated from the Dart file above.
