package function

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/constants/function/on_will_pop.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:fluttertoast/fluttertoast.dart';

Future<bool> onWillPop(
    {required Function(DateTime?) action, DateTime? currentBackPressTime}) {
  DateTime now = DateTime.now();
  if (currentBackPressTime == null ||
      now.difference(currentBackPressTime) > const Duration(seconds: 3)) {
    action(now);
    Fluttertoast.showToast(msg: "Nhấn thêm lần nữa để thoát");
    return Future.value(false);
  }
  return Future.value(true);
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
// TODO: add functions / types translated from the Dart file above.
