package constants

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/constants/app_colors.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:flutter/material.dart';

class AppColors {
  static Color whisperBackground = const Color.fromRGBO(244, 239, 243, 1);
  static Color buttonLogin = const Color.fromRGBO(252, 107, 104, 1);
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
type AppColors struct {
	// TODO: add fields translated from Dart
}

