package bloc

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/page/signup/bloc/signup_event.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:spending_management/models/user.dart';

abstract class SignupEvent {}

class SignupEmailPasswordEvent extends SignupEvent {
  final String email;
  final String password;
  final User user;

  SignupEmailPasswordEvent(
      {required this.email, required this.password, required this.user});
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
type SignupEvent struct {
	// TODO: add fields translated from Dart
}

type SignupEmailPasswordEvent struct {
	// TODO: add fields translated from Dart
}

