package bloc

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/page/signup/bloc/singup_state.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
abstract class SignupState {}

class InitState extends SignupState {}

class SignupSuccessState extends SignupState {}

class SignupErrorState extends SignupState {
  String status;
  SignupErrorState({required this.status});
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
type SignupState struct {
	// TODO: add fields translated from Dart
}

type InitState struct {
	// TODO: add fields translated from Dart
}

type SignupSuccessState struct {
	// TODO: add fields translated from Dart
}

type SignupErrorState struct {
	// TODO: add fields translated from Dart
}

