package signup

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/page/signup/gender_widget.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:spending_management/setting/localization/app_localizations.dart';
import 'package:flutter/material.dart';
import 'package:spending_management/constants/app_colors.dart';
import 'package:spending_management/constants/app_styles.dart';

class GenderWidget extends StatelessWidget {
  const GenderWidget({
    Key? key,
    required this.action,
    required this.gender,
    required this.currentGender,
  }) : super(key: key);
  final bool currentGender;
  final bool gender;
  final Function action;

  @override
  Widget build(BuildContext context) {
    return InkWell(
      splashColor: Colors.transparent,
      onTap: () {
        action();
      },
      child: Container(
        padding: const EdgeInsets.all(10),
        decoration: BoxDecoration(
          color: gender == currentGender
              ? Colors.white24
              : AppColors.whisperBackground,
          border: Border.all(
            color: gender == currentGender
                ? Colors.black12
                : AppColors.whisperBackground,
          ),
          borderRadius: BorderRadius.circular(10),
        ),
        child: Column(
          children: [
            Text(
              gender
                  ? AppLocalizations.of(context).translate('male')
                  : AppLocalizations.of(context).translate('female'),
              style: AppStyles.p,
            ),
            const SizedBox(height: 10),
            Image.asset(
              gender ? 'assets/images/male.png' : 'assets/images/female.png',
              width: 100,
            ),
          ],
        ),
      ),
    );
  }
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
type GenderWidget struct {
	// TODO: add fields translated from Dart
}

