package models

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/models/filter.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:flutter/material.dart';

class Filter {
  List<int> chooseIndex;
  int money;
  int finishMoney;
  DateTime? time;
  DateTime? finishTime;
  String note;
  List<Color>? colors;
  List<String>? friends;

  Filter({
    required this.chooseIndex,
    this.money = 0,
    this.finishMoney = 0,
    this.time,
    this.finishTime,
    this.note = "",
    this.colors,
    this.friends,
  });

  Filter copyWith({
    List<int>? chooseIndex,
    int? money,
    int? finishMoney,
    DateTime? time,
    DateTime? finishTime,
    String? note,
    List<Color>? colors,
    List<String>? friends,
  }) {
    return Filter(
      chooseIndex: chooseIndex ?? List.from(this.chooseIndex),
      money: money ?? this.money,
      finishMoney: finishMoney ?? this.finishMoney,
      time: time ?? this.time,
      finishTime: finishTime ?? this.finishTime,
      note: note ?? this.note,
      colors: colors ?? this.colors,
      friends: friends ?? this.friends,
    );
  }
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
type Filter struct {
	// TODO: add fields translated from Dart
}

