package widget

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/page/main/profile/widget/setting_item.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:flutter/material.dart';

Widget settingItem(
    {required String text,
    required Function action,
    required IconData icon,
    Color? color}) {
  return InkWell(
    onTap: () {
      action();
    },
    child: Row(
      children: [
        Container(
          decoration: BoxDecoration(
            color: color ?? Colors.black45,
            borderRadius: BorderRadius.circular(90),
          ),
          padding: const EdgeInsets.all(10),
          child: Icon(icon, color: Colors.white),
        ),
        const SizedBox(width: 10),
        Text(text, style: const TextStyle(fontSize: 18)),
        const Spacer(),
        const Icon(Icons.arrow_forward_ios_outlined)
      ],
    ),
  );
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
// TODO: add functions / types translated from the Dart file above.
