package widget

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/page/main/analytic/widget/tabbar_chart.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:spending_management/constants/app_styles.dart';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

Widget tabBarChart({required TabController controller}) {
  return Container(
    height: 45,
    width: 110,
    decoration: BoxDecoration(
      color: const Color.fromRGBO(242, 243, 247, 1),
      borderRadius: BorderRadius.circular(90),
    ),
    child: TabBar(
        controller: controller,
        labelColor: const Color(0xff2c4260),
        labelStyle: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
        unselectedLabelColor: const Color.fromRGBO(45, 216, 198, 1),
        unselectedLabelStyle: AppStyles.p,
        isScrollable: false,
        indicatorSize: TabBarIndicatorSize.tab,
        indicatorPadding: const EdgeInsets.all(5),
        indicator: const BoxDecoration(
          color: Color.fromRGBO(45, 216, 198, 1),
          shape: BoxShape.circle,
        ),
        tabs: const [
          Icon(FontAwesomeIcons.chartColumn),
          Icon(FontAwesomeIcons.chartPie),
        ]),
  );
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
// TODO: add functions / types translated from the Dart file above.
