package widget

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/page/main/analytic/widget/total_report.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:spending_management/models/spending.dart';
import 'package:spending_management/page/main/analytic/widget/box_text.dart';
import 'package:spending_management/setting/localization/app_localizations.dart';
import 'package:flutter/material.dart';

class TotalReport extends StatelessWidget {
  const TotalReport({Key? key, required this.list}) : super(key: key);
  final List<Spending> list;

  @override
  Widget build(BuildContext context) {
    List<Spending> spendingList =
        list.where((element) => element.money < 0).toList();

    int spending = spendingList.isEmpty
        ? 0
        : spendingList
            .map((e) => e.money)
            .reduce((value, element) => value + element);

    spendingList = list.where((element) => element.money > 0).toList();

    int income = spendingList.isEmpty
        ? 0
        : spendingList
            .map((e) => e.money)
            .reduce((value, element) => value + element);

    return Column(
      children: [
        const SizedBox(height: 10),
        Row(
          children: [
            Expanded(
              child: boxText(
                text: "${AppLocalizations.of(context).translate('spending')}: ",
                number: spending,
                color: Colors.red,
              ),
            ),
            const SizedBox(width: 5),
            Expanded(
              child: boxText(
                text: "${AppLocalizations.of(context).translate('income')}: ",
                number: income,
                color: Colors.blue,
              ),
            )
          ],
        ),
        const SizedBox(height: 10),
        boxText(
          text:
              "${AppLocalizations.of(context).translate('revenue_expenditure')}: ",
          number: income + spending,
        ),
        const SizedBox(height: 10),
      ],
    );
  }
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
type TotalReport struct {
	// TODO: add fields translated from Dart
}

