package widget

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/page/main/widget/item_bottom_tab.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:flutter/material.dart';

Widget itemBottomTab({
  required String text,
  required int index,
  required int current,
  required IconData icon,
  required Function action,
  double? size,
}) {
  return MaterialButton(
    minWidth: 40,
    onPressed: () {
      action();
    },
    child: Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Icon(
          icon,
          color: current == index
              ? const Color.fromRGBO(173, 149, 121, 1)
              : Colors.grey,
          size: size,
        ),
        const SizedBox(height: 5),
        Text(
          text,
          style: TextStyle(
            color: current == index
                ? const Color.fromRGBO(173, 149, 121, 1)
                : Colors.grey,
          ),
        )
      ],
    ),
  );
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
// TODO: add functions / types translated from the Dart file above.
