package bloc

// Code generated by dart2go-skeleton (quick pass). DO NOT EDIT BY HAND.
// Original file: lib/setting/bloc/setting_state.dart
// Notes:
// - This is a structural skeleton to help migrate from Dart to Go while *keeping directory layout*.
// - Original Dart source is embedded below in comments for reference.
// - Replace TODOs with real implementations.
// - Consider organizing packages and moving UI-specific code out; Flutter UI has no direct Go equivalent.

/*
----- BEGIN ORIGINAL DART CODE -----
import 'package:flutter/material.dart';

abstract class SettingState {
  final Locale locale;
  final bool isDark;
  const SettingState(this.locale, this.isDark);
}

class SettingChange extends SettingState {
  const SettingChange(Locale locale, bool isDark) : super(locale, isDark);
}

----- END ORIGINAL DART CODE -----
*/

// === AUTO-GENERATED SKELETONS ===
type SettingState struct {
	// TODO: add fields translated from Dart
}

type SettingChange struct {
	// TODO: add fields translated from Dart
}

